import 'package:mp_flutter_chart/chart/mp/core/data_set/data_set.dart';
import 'package:mp_flutter_chart/chart/mp/core/entry/entry.dart';

mixin OnDrawListener {
  /**
   * Called whenever an entry is added with the finger. Note this is also called for entries that are generated by the
   * library, when the touch gesture is too fast and skips points.
   *
   * @param entry
   *            the last drawn entry
   */
  void onEntryAdded(Entry entry);

  /**
   * Called whenever an entry is moved by the user after beeing highlighted
   *
   * @param entry
   */
  void onEntryMoved(Entry entry);

  /**
   * Called when drawing finger is lifted and the draw is finished.
   *
   * @param dataSet
   *            the last drawn DataSet
   */
  void onDrawFinished(DataSet<Entry> dataSet);
}
